strictness: high
doc-warnings: false
test-warnings: true
ignore-paths:
  # vendored
  - nixipy/nix.py

pep8:
  disable:
    - N806  # variable in function should be lowercase

pep257:
  disable:
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D107

pyroma:
  run: true

vulture:
  run: true
