env:
  global:
    - CC_TEST_REPORTER_ID=2c40573e965dbf461ec74dee5b4b4ce51dd3b099ba50e946ba5423dd831cf17f
language: nix
before_script: pip3 install --user codeclimate-test-reporter codecov
script: nix-shell --run pytest
after_script:
  - codeclimate-test-reporter
  - codecov
