[run]
omit = [
    "distinfo/__main__.py",
    "distinfo/cli.py",
    "distinfo/command.py",
    "distinfo/collector/*",
    "distinfo/logconfig.py",
    "tests/acceptance/*",
    "tests/functional/*",
]

[report]
exclude_lines = [
    "pragma: no utest cover",
    "pragma: no utest ftest cover",
]
