[run]
omit = [
    "distinfo/__main__.py",
    "distinfo/cli.py",
    "tests/acceptance/*",
    "tests/unit/*",
]

[report]
exclude_lines = [
    "pragma: no ftest cover",
    "pragma: no utest ftest cover",
    "pragma: no ftest ptest cover",
]
