[html]
title = "Acceptance Test Coverage Report"

[report]
exclude_lines = [
    "pragma: no ptest cover",
    "pragma: no ftest ptest cover",
]
omit = [
    "tests/functional/*",
    "tests/unit/*",
]
