# whitelist for vulture
# ruff: noqa
# type: ignore
_.data_file  # unused attribute (.skel/covcfg.py:22)
_.data_file  # unused attribute (covcfg.py:22)
SERIAL  # unused variable (distinfo/const.py:10)
supported_platform  # unused variable (distinfo/distribution.py:58)
description_content_type  # unused variable (distinfo/distribution.py:64)
download_url  # unused variable (distinfo/distribution.py:71)
author  # unused variable (distinfo/distribution.py:74)
author_email  # unused variable (distinfo/distribution.py:76)
maintainer  # unused variable (distinfo/distribution.py:78)
maintainer_email  # unused variable (distinfo/distribution.py:80)
classifier  # unused variable (distinfo/distribution.py:84)
requires_external  # unused variable (distinfo/distribution.py:88)
provides_dist  # unused variable (distinfo/distribution.py:92)
obsoletes_dist  # unused variable (distinfo/distribution.py:94)
_.handlers  # unused attribute (distinfo/logconfig.py:56)
_.isatty  # unused attribute (distinfo/logconfig.py:59)
_._startTime  # unused attribute (distinfo/logconfig.py:64)
_.warn  # unused attribute (distinfo/monkey.py:24)
_.pinned  # unused property (distinfo/requirement.py:39)
_logsetup  # unused function (tests/conftest.py:11)
_patch_requirement_hash  # unused function (tests/conftest.py:18)
_setenv  # unused function (tests/conftest.py:25)
