name: Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUFF_FORMAT: github
      SKIP: mypy
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: make lint
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: failure()
        with:
          commit_message: auto linted
  test:
    runs-on: ubuntu-latest
    env:
      COV_REPORT: xml
    strategy:
      matrix:
        test:
          - utest
          - ftest
          - atest
    steps:
      - uses: 0compute/pyproject@main
        with:
          cachix-authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: actions/cache@v3
        with:
          path: /var/tmp/distinfo-test-packages
          key: test-packages-${{ hashFiles('tests/acceptance/test_packages.yaml') }}
      - run: make ${{ matrix.test }}
      - uses: coverallsapp/github-action@v2
        with:
          file: coverage-${{ matrix.test }}.xml
          flag-name: ${{ matrix.test }}
          parallel: true
  coveralls:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: ${{ join(matrix.*, ',') }}
