name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      ARGS: -vv
      COV_REPORT: xml
      RUFF_FORMAT: github
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: /var/tmp/distinfo-test-packages
          key: test-packages-${{ hashFiles('tests/acceptance/test_packages.yaml') }}
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v12
        with:
          name: distinfo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: HatsuneMiku3939/direnv-action@v1
      - run: ruff check .
      - run: make utest
      - run: make ftest
      - run: make atest
        env:
          ARGS: -xvv --flake-finder
      - run: make coverage-combined
      - uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.xml
