name: Test Report

on:
  workflow_run:
    workflows:
      - Check
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - unit
          - functional
          - acceptance
    steps:
      - uses: dorny/test-reporter@v1.7.0
        with:
          artifact: test-result
          name: ${{ matrix.test }}
          path: pytest-${{ matrix.test }}.xml
          reporter: java-junit
